Pouch/routes/web.php
<?php

use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\CicloController;
use App\Http\Controllers\PerfilController;
use App\Http\Controllers\ProfesorController;
use App\Http\Controllers\ProyectoController;
use Illuminate\Support\Facades\Route;
use App\Models\Proyecto;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (auth()->user()) {
        return redirect()->route('inicio');
    }
    return view('welcome');
})->name('home');

Route::middleware(['auth:sanctum', 'verified'])->get('inicio',[HomeController::class,'index'])->name('inicio');

Route::resource('admin/users',UserController::class)->only(['index','edit','update'])->middleware(['auth:sanctum', 'verified'])->names('admin.users');

Route::middleware(['auth:sanctum', 'verified'])->get('ciclos', [CicloController::class, 'index'])->name('ciclos.index');

Route::middleware(['auth:sanctum', 'verified'])->get('ciclos/{ciclo}', [CicloController::class, 'show'])->name('ciclos.show');

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/mis-proyectos', [ProyectoController::class, 'personales'])->name('proyectos.personales');

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/mis-proyectos/{proyecto}/asignarUsuarios', [ProyectoController::class, 'asignarUsuarios'])->name('proyectos.asignarUsuarios');

Route::middleware(['auth:sanctum', 'verified'])->post('proyectos/mis-proyectos/{proyecto}/asignarUsuarios', [ProyectoController::class, 'asignar'])->name('proyectos.asignar');

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/mis-proyectos/{proyecto}/desasignar/{user}', [ProyectoController::class, 'desasignar'])->name('proyectos.desasignar');

Route::middleware(['auth:sanctum', 'verified'])->post('proyectos/{proyecto}/comentar', [ProyectoController::class, 'comentar'])->name('proyectos.comentar');

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/{proyecto}/eliminarComentario', [ProyectoController::class, 'eliminarComentario'])->name('proyectos.eliminarComentario');

Route::middleware(['auth:sanctum', 'verified','can:proyectos.evaluar.index'])->get('proyectos/evaluar', [ProyectoController::class, 'evaluarIndex'])->name('proyectos.evaluar.index');

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/evaluar/{proyecto}', [ProyectoController::class, 'evaluarSecciones'])->name('proyecto.secciones');

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/evaluar/{proyecto}/exposicion',[ProyectoController::class,'evaluarExposicion'])->name('proyecto.evaluarExposicion');

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/evaluar/{proyecto}/documentacion',[ProyectoController::class,'evaluarDocumentacion'])->name('proyecto.evaluarDocumentacion');

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/evaluar/{proyecto}/aplicacion',[ProyectoController::class,'evaluarAplicacion'])->name('proyecto.evaluarAplicacion');

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/evaluar/{proyecto}/seguimiento',[ProyectoController::class,'evaluarSeguimiento'])->name('proyecto.evaluarSeguimiento');

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/evaluar/{proyecto}/registrarPuntuacion',[ProyectoController::class,'registrarPuntuacion'])->name('proyecto.registrarPuntuacion');

Route::resource('proyectos', ProyectoController::class)->names('proyectos')->middleware(['auth:sanctum', 'verified']);

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/{proyecto}/descargar', [ProyectoController::class, 'download'])->name('proyectos.download');

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/{proyecto}/descargarLogo', [ProyectoController::class, 'descargarLogo'])->name('proyectos.descargarLogo');

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/{proyecto}/descargarRecurso/{recurso}', [ProyectoController::class, 'descargarRecurso'])->name('proyectos.descargarRecurso');

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/{proyecto}/mostrarPDF', [ProyectoController::class, 'mostrarPDF'])->name('proyectos.mostrarPDF');

Route::middleware(['auth:sanctum', 'verified'])->get('perfil/{user}', [PerfilController::class, 'index'])->name('perfil');

Route::middleware(['auth:sanctum', 'verified'])->get('profesores/rubricas',[ProfesorController::class,'index'])->name('profesores');

/*Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');*/

Pouch/app/Http/Controllers/ProyectoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProyectoRequest;
use App\Models\CalificacionDet;
use App\Models\Ciclo;
use App\Models\Comentario;
use App\Models\Proyecto;
use App\Models\Recurso;
use App\Models\RubricaAplicacionDet;
use App\Models\RubricaDocumentacionCab;
use App\Models\RubricaDocumentacionDet;
use App\Models\RubricaExposicionDet;
use App\Models\RubricaSeguimientoDet;
use App\Models\TipoRecurso;
use App\Models\User;
use App\Traits\ControlUsersTrait;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use ZipArchive;
use File;
use Illuminate\Support\Facades\DB;

class ProyectoController extends Controller
{
    use ControlUsersTrait;

    public function __construct()
    {
        //$this->middleware('can:proyectos.evaluar.index');
    }

    public function index()
    {
        return view('proyectos.index');
    }

    public function create()
    {
        $ciclos = Ciclo::all();
        return view('proyectos.create', compact('ciclos'));
    }

    public function store(ProyectoRequest $request)
    {
        $publico = 1;
        if (!$request->has('publico')) {
            $publico = 0;
        }

        $proyecto = new Proyecto();
        $proyecto->fill($request->all());
        $proyecto->publico = $publico;
        $proyecto->created_at = Carbon::now()->toDateTimeString();
        $proyecto->updated_at =Carbon::now()->toDateTimeString();
        $proyecto->save();

        $this->registrarControlUsers($proyecto->id, "PROYECTO CREADO");

        if ($request->file('ruta_logo')) {
            $nombreArchivo = $request->file('ruta_logo')->getClientOriginalName();
            $proyecto->update([
                'ruta_logo' => Storage::putFileAs('recursos/' . $proyecto->id, $request->file('ruta_logo'), $nombreArchivo)
            ]);
            $this->registrarControlUsers($proyecto->id, "LOGO SUBIDO");
        } else {
            $proyecto->update([
                'ruta_logo' => Storage::putFileAs('recursos/' . $proyecto->id, 'images/defaultwhite.jpg', 'defaultwhite.jpg')
            ]);
        }

        if ($request->file('ruta_fichero')) {
            $nombreArchivo = $request->file('ruta_fichero')->getClientOriginalName();
            $urlFile = Storage::putFileAs('recursos/' . $proyecto->id, $request->file('ruta_fichero'), $nombreArchivo);
            $extension = pathinfo($urlFile, PATHINFO_EXTENSION);

            $proyecto->recursos()->create([
                'ruta_fichero' => $urlFile,
                'tipo_id' => TipoRecurso::where('descripcion', 'LIKE', '%' . $extension . '%')->first()->id
            ]);
            $this->registrarControlUsers($proyecto->id, "CÓDIGO DEL PROYECTO SUBIDO");
        }

        if ($request->file('ruta_documentacion')) {
            $nombreArchivo = $request->file('ruta_documentacion')->getClientOriginalName();
            $urlFile = Storage::putFileAs('recursos/' . $proyecto->id, $request->file('ruta_documentacion'), $nombreArchivo);
            $extension = pathinfo($urlFile, PATHINFO_EXTENSION);
            $proyecto->recursos()->create([
                'ruta_fichero' => $urlFile,
                'tipo_id' => TipoRecurso::where('descripcion', 'LIKE', '%' . $extension . '%')->first()->id
            ]);
            $this->registrarControlUsers($proyecto->id, "DOCUMENTACIÓN DEL PROYECTO SUBIDO");
        }
        return redirect()->route('proyectos.show', $proyecto)->with('createInfo', 'Proyecto creado');
    }

    public function show(Proyecto $proyecto)
    {
        $registros = $proyecto->user->registros->where('proyecto_id', $proyecto->id); 
        

        // LOGO
        $ultimosRegistros[] = $registros->sortByDesc('created_at')->first(function ($item){
            return false !== stristr($item->accion, 'LOGO');
        });

        //CÓDIGO
        $ultimosRegistros[]  = $registros->sortByDesc('created_at')->first(function ($item){
            return false !== stristr($item->accion, 'CÓDIGO');
        });

        //DOCUMENTACIÓN
        $ultimosRegistros[]  = $registros->sortByDesc('created_at')->first(function ($item){
            return false !== stristr($item->accion, 'DOCUMENTACIÓN');
        });
        $ultimosRegistros[] = $registros->last();
        $ultimosRegistros = array_filter($ultimosRegistros, fn($value) => !is_null($value) && $value !== '');
        $ultimosRegistros = collect($ultimosRegistros)->sortByDesc('created_at');
        return view('proyectos.show', compact('proyecto','ultimosRegistros'));
    }

    public function edit(Proyecto $proyecto)
    {
        $this->authorize('author', $proyecto);
        $ciclos = Ciclo::all();
        return view('proyectos.edit', compact('proyecto', 'ciclos'));
    }

    public function update(ProyectoRequest $request, Proyecto $proyecto)
    {
        $this->authorize('author', $proyecto);

        $publico = 1;
        if (!$request->has('publico')) {
            $publico = 0;
        }

        $url_logo_delete = $proyecto->ruta_logo;
        $proyecto->fill($request->all());
        $proyecto->publico = $publico;

        if ($request->file('ruta_logo')) {
            Storage::delete(($url_logo_delete));
            $nombreArchivo = $request->file('ruta_logo')->getClientOriginalName();
            $proyecto->update([
                'ruta_logo' => Storage::putFileAs('recursos/' . $proyecto->id, $request->file('ruta_logo'), $nombreArchivo)
            ]);
            $this->registrarControlUsers($proyecto->id, "LOGO MODIFICADO");
        }

        $proyecto->save();

        if ($request->file('ruta_fichero')) {

            $nombreArchivo = $request->file('ruta_fichero')->getClientOriginalName();
            $urlFile = Storage::putFileAs('recursos/' . $proyecto->id, $request->file('ruta_fichero'), $nombreArchivo);
            $extension = pathinfo($urlFile, PATHINFO_EXTENSION);
            $recurso = $proyecto->recursos->whereIn('tipo_id', [1, 2])->first();

            if ($recurso) {
                Storage::delete($recurso->ruta_fichero);
                $recurso->update([
                    'ruta_fichero' => $urlFile,
                    'tipo_id' => TipoRecurso::where('descripcion', 'LIKE', '%' . $extension . '%')->first()->id
                ]);
                $this->registrarControlUsers($proyecto->id, "CÓDIGO DEL PROYECTO MODIFICADO");
            } else {
                $proyecto->recursos()->create([
                    'ruta_fichero' => $urlFile,
                    'tipo_id' => TipoRecurso::where('descripcion', 'LIKE', '%' . $extension . '%')->first()->id
                ]);
                $this->registrarControlUsers($proyecto->id, "CÓDIGO DEL PROYECTO SUBIDO");
            }
        }

        if ($request->file('ruta_documentacion')) {
            $nombreArchivo = $request->file('ruta_documentacion')->getClientOriginalName();
            $urlFile = Storage::putFileAs('recursos/' . $proyecto->id, $request->file('ruta_documentacion'), $nombreArchivo);
            $extension = pathinfo($urlFile, PATHINFO_EXTENSION);
            $recurso = $proyecto->recursos->whereIn('tipo_id', [3, 4])->first();

            if ($recurso) {
                Storage::delete($recurso->ruta_fichero);
                $recurso->update([
                    'ruta_fichero' => $urlFile,
                    'tipo_id' => TipoRecurso::where('descripcion', 'LIKE', '%' . $extension . '%')->first()->id
                ]);
                $this->registrarControlUsers($proyecto->id, "DOCUMENTACIÓN DEL PROYECTO MODIFICADO");
            } else {
                $proyecto->recursos()->create([
                    'ruta_fichero' => $urlFile,
                    'tipo_id' => TipoRecurso::where('descripcion', 'LIKE', '%' . $extension . '%')->first()->id
                ]);
                $this->registrarControlUsers($proyecto->id, "DOCUMENTACIÓN DEL PROYECTO SUBIDO");
            }
        }

        return redirect()->route('proyectos.edit', $proyecto)->with('updateInfo', 'Proyecto actualizado con éxito');
    }

    public function download(Proyecto $proyecto)
    {
        if ($proyecto->publico) {
            $zip = new ZipArchive;
            $fileName = $proyecto->nombre . ".rar";
            Storage::makeDirectory('proyectos/' . $proyecto->id);
            if ($zip->open(public_path('storage/proyectos/' . $proyecto->id . '/' . $fileName), ZipArchive::CREATE) === true) {
                $files = File::files(public_path('storage/recursos/' . $proyecto->id));
                foreach ($files as $key => $value) {
                    $relativeNameInZipFile = basename($value);
                    $zip->addFile($value, $relativeNameInZipFile);
                }
                $zip->close();
            }
            $proyecto->update([
                'descargas' => $proyecto->descargas + 1
            ]);
            return response()->download(public_path('storage/proyectos/' . $proyecto->id . '/' . $fileName))->deleteFileAfterSend(true);
        }
        return redirect()->route('inicio');
    }

    public function personales()
    {
        $proyectos = Proyecto::all();
        return view('proyectos.personales', compact('proyectos'));
    }

    public function destroy(Proyecto $proyecto)
    {
        $this->authorize('author', $proyecto);
        $proyecto->delete();
        Storage::deleteDirectory('proyectos/' . $proyecto->id);
        Storage::deleteDirectory('recursos/' . $proyecto->id);
        return redirect()->route('proyectos.personales')->with('destroyInfo', 'El proyecto se ha eliminado con éxito');
    }

    public function comentar(Request $request, Proyecto $proyecto)
    {
        Comentario::create([
            'proyecto_id' => $proyecto->id,
            'user_id' => auth()->user()->id,
            'descripcion' => $request->comentario
        ]);
        return redirect()->route('proyectos.show', $proyecto)->with('comentarioInfo', 'El comentario se ha insertado con éxito');

Pouch/app/Http/Livewire/Admin/UsersIndex.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;
class UsersIndex extends Component
{
    use WithPagination;
    protected $paginationTheme = "bootstrap";
    public $search;

    public function updatingSearch(){
        $this->resetPage();
    } 
    
    public function render()
    {
        /*$users = User::where('name','LIKE','%' . $this->search . '%')
        ->orWhere('email','LIKE','%' . $this->search . '%')
        ->paginate();*/
        $users = User::all();

        return view('livewire.admin.users-index',compact('users'));
    }
}

Pouch/app/Http/Livewire/Ciclo/CiclosIndex.php
<?php

namespace App\Http\Livewire\Ciclo;

use App\Models\Ciclo;
use Livewire\Component;
use Livewire\WithPagination;

class CiclosIndex extends Component
{
    public function render()
    {
        $ciclosSecciones = Ciclo::select('seccion')->groupByRaw('seccion')->get();
        return view('livewire.ciclo.ciclos-index', compact('ciclosSecciones'));
    }
}

Pouch/app/Http/Livewire/Proyecto/ProyectosEvaluarIndex.php
<?php

namespace App\Http\Livewire\Proyecto;

use Livewire\Component;

class ProyectosEvaluarIndex extends Component
{
    public function render()
    {
        $proyectos = auth()->user()->proyectosAsociados;
        return view('livewire.proyecto.proyectos-evaluar-index',compact('proyectos'));
    }
}

Pouch/app/Http/Livewire/Proyecto/ProyectosIndex.php
<?php

namespace App\Http\Livewire\Proyecto;

use App\Models\Proyecto;
use Livewire\Component;

class ProyectosIndex extends Component
{

    public function render()
    {
        $proyectos = Proyecto::orderByDesc('created_at')->get();
        return view('livewire.proyecto.proyectos-index', compact('proyectos'));
    }
}

Pouch/app/Http/Livewire/Proyecto/ProyectosPersonales.php
<?php

namespace App\Http\Livewire\Proyecto;

use App\Models\Proyecto;
use Livewire\Component;
use Livewire\WithPagination;


class ProyectosPersonales extends Component
{

    use WithPagination;
    public $search;

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        $proyectos = Proyecto::latest('created_at')
            ->where('user_id',auth()->user()->id)
            ->get();
        return view('livewire.proyecto.proyectos-personales', compact('proyectos'));
    }
}

Pouch/resources/views/livewire/proyecto/proyectos-evaluar-index.blade.php
<div>
    <div class="card">
        <div class="card-header bg-dark p-0 py-2">
            <section class="content-header">
                <h3 class="card-title text-bold"><span class="fas fa-fx fa-file-alt"></span> LISTA DE PROYECTOS ASIGNADOS</h3>
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a class="text-white" href="{{ route('inicio') }}">Inicio</a></li>
                    <li class="breadcrumb-item active text-white-50">Evaluar proyecto</li>
                </ol>
            </section>
        </div>
        <div class="card-body">
            <table class="table table-striped" id="users">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Autor</th>
                        <th>Ciclo Formativo</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($proyectos as $proyecto)
                        <tr>
                            <td>{{$proyecto->nombre}}</td>
                            <td>{{$proyecto->user->name}}</td>
                            <td>{{$proyecto->ciclo->nombre}}</td>
                            <td>
                                <a class="btn btn-primary" href="{{route('proyecto.secciones',$proyecto)}}">Evaluar proyecto</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

Pouch/resources/views/livewire/proyecto/proyectos-index.blade.php
<div>
    <div class="card">
        <div class="card-header bg-success p-0 py-2">
            <section class="content-header">
                <h3 class="card-title text-bold"><i class="fas fa-fx fa-list"></i> LISTA DE PROYECTOS DE OTROS ALUMNOS</h3>
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a class="text-white" href="{{ route('inicio') }}">Inicio</a></li>
                    <li class="breadcrumb-item active text-white-50">Lista de proyectos</li>
                </ol>
            </section>
        </div>
        <div class="card-body">
            <table class="table table-striped" id="proyectos">
                <thead>
                    <tr>
                        <th style="width: 8%">
                            Autor
                        </th>
                        <th style="width: 25%">
                            Nombre del proyecto
                        </th>
                        <th style="width: 20%">
                            Ciclo Formativo
                        </th>
                        <th style="width: 20%">
                            Progreso del proyecto
                        </th>
                        <th style="width: 8%">
                            Descargas
                        </th>
                        <th style="width: 8%" class="text-center">
                            Estado
                        </th>
                        <th style="width: 18%">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($proyectos as $proyecto)
                        <tr>
                            <td>
                                <ul class="list-inline mt-2 mb-0">
                                    <li class="list-inline-item">
                                        <div class="container-overlay">
                                            <a href="{{ route('perfil', $proyecto->user) }}">
                                                <img alt="Avatar" id="avatar" title="{{ $proyecto->user->name }}"
                                                    class="table-avatar img-circle"
                                                    src="{{ $proyecto->user->adminlte_image() }}">
                                                <div class="overlay table-avatar img-circle"
                                                    style="background-color:rgba(26, 19, 19, 0.76)">
                                                    {{ $proyecto->user->name }}</div>
                                            </a>
                                        </div>
                                    </li>
                                </ul>
                            </td>
                            <td>
                                <a class="text-bold" href="{{ route('proyectos.show', $proyecto) }}">
                                    {{ $proyecto->nombre }}
                                </a>
                                <br />
                                @if ($proyecto->created_at == $proyecto->updated_at)
                                    <small>
                                        Publicado hace {{ $proyecto->calcularTiempo($proyecto->created_at) }}
                                    </small>
                                @else
                                    <small>
                                        Actualizado hace {{ $proyecto->calcularTiempo($proyecto->updated_at) }}
                                    </small>
                                @endif
                            </td>
                            <td>
                                <i>{{ $proyecto->ciclo->nombre }}</i>
                            </td>
                            <td class="project_progress">
                                <div class="progress progress-sm">
                                    @php
                                        $random = rand(0, 100);
                                    @endphp
                                    @if ($random < 25)
                                        <div class="progress-bar bg-success progress-bar-striped progress-bar-animated"
                                            role="progressbar" aria-valuenow="{{ $random }}" aria-valuemin="0"
                                            aria-valuemax="100" style="width:{{ $random }}%">
                                        </div>

                                    @elseif ($random < 50) <div
                                            class="progress-bar bg-info progress-bar-striped progress-bar-animated"
                                            role="progressbar" aria-valuenow="{{ $random }}" aria-valuemin="0"
                                            aria-valuemax="100" style="width:{{ $random }}%">
                                </div>

                            @elseif ($random < 75) <div
                                    class="progress-bar bg-warning progress-bar-striped progress-bar-animated"
                                    role="progressbar" aria-valuenow="{{ $random }}" aria-valuemin="0"
                                    aria-valuemax="100" style="width:{{ $random }}%">
        </div>

    @elseif ($random <= 100) <div class="progress-bar bg-danger progress-bar-striped progress-bar-animated"
            role="progressbar" aria-valuenow="{{ $random }}" aria-valuemin="0" aria-valuemax="100"
            style="width:{{ $random }}%">
    </div>
    @endif
</div>
<small>
    {{ $random }}% Completado
</small>
</td>
<td>
    <i class="fas fa-fx fa-cloud-download-alt"> </i> {{ $proyecto->descargas }}
</td>
<td class="project-state">
    @if ($proyecto->publico)
        <span class="badge badge-success">Público</span>
    @else
        <span class="badge badge-danger">Privado</span>
    @endif
</td>
<td class="project-actions text-right">
    <a class="btn btn-primary btn-sm" href="{{ route('proyectos.show', $proyecto) }}">
        Ver Proyecto
    </a>
</td>
</tr>
@endforeach
</tbody>
</table>
</div>
</div>

</div>

Pouch/resources/views/livewire/proyecto/proyectos-personales.blade.php
<div>
    <div class="card">
        <div class="card-header bg-success p-0 py-2">
            <section class="content-header">
                <h3 class="card-title text-bold"><i class="fas fa-fx fa-crown"></i> LISTA DE MIS PROYECTOS PERSONALES</h3>
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a class="text-white" href="{{ route('inicio') }}">Inicio</a></li>
                    <li class="breadcrumb-item active text-white-50">Mis proyectos</li>
                </ol>
            </section>
        </div>
        <div class="card-body">
            <table class="table table-striped" id="proyectosPersonales">
                <thead>
                    <tr>
                        <th style="width: 25%">
                            Nombre del proyecto
                        </th>
                        <th style="width: 20%">
                            Progreso del proyecto
                        </th>
                        <th style="width: 20%">
                            Ciclo Formativo
                        </th>
                        <th style="width: 3%" class="text-center">
                            Estado
                        </th>
                        <th>
                            Puntuación
                        </th>
                        <th style="width: 5%">
                        </th>
                        <th style="width: 5%">
                        </th>
                        <th style="width: 5%">
                        </th>
                        <th style="width: 5%">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($proyectos as $proyecto)
                        <tr>
                            <td>
                                <a href="{{ route('proyectos.show', $proyecto) }}">
                                    {{ $proyecto->nombre }}
                                </a>
                                <br />
                                <small>
                                    Publicado el {{ $proyecto->created_at->format('d-m-Y') }}
                                </small>
                            </td>
                            <td class="project_progress">
                                <div class="progress progress-sm">
                                    @php
                                        $random = rand(0, 100);
                                    @endphp
                                    @if ($random < 25)
                                        <div class="progress-bar bg-success progress-bar-striped progress-bar-animated"
                                            role="progressbar" aria-valuenow="{{ $random }}" aria-valuemin="0"
                                            aria-valuemax="100" style="width:{{ $random }}%">
                                        </div>

                                    @elseif ($random < 50) <div
                                            class="progress-bar bg-info progress-bar-striped progress-bar-animated"
                                            role="progressbar" aria-valuenow="{{ $random }}" aria-valuemin="0"
                                            aria-valuemax="100" style="width:{{ $random }}%">
                                </div>

                            @elseif ($random < 75) <div
                                    class="progress-bar bg-warning progress-bar-striped progress-bar-animated"
                                    role="progressbar" aria-valuenow="{{ $random }}" aria-valuemin="0"
                                    aria-valuemax="100" style="width:{{ $random }}%">
        </div>

    @elseif ($random <= 100) <div class="progress-bar bg-danger progress-bar-striped progress-bar-animated"
            role="progressbar" aria-valuenow="{{ $random }}" aria-valuemin="0" aria-valuemax="100"
            style="width:{{ $random }}%">
    </div>
    @endif
</div>
<small>
    {{ $random }}% Completado
</small>
</td>
<td>
    <i>{{ $proyecto->ciclo->nombre }}</i>
</td>
<td class="project-state">
    @if ($proyecto->publico)
        <span class="badge badge-success">Público</span>
    @else
        <span class="badge badge-danger">Privado</span>
    @endif
</td>
<td>
    @if (empty($proyecto->puntuacion))
        <p>Sin evaluar</p>
    @else
        <p>{{ $proyecto->puntuacion }} / 100</p>
    @endif
</td>
<td>
    <a class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Ver Proyecto"
        href="{{ route('proyectos.show', $proyecto) }}">
        <i class="fas fa-eye m-auto">
        </i>
    </a>
</td>
<td>
    <a class="btn btn-info" data-toggle="tooltip" data-placement="top" title="Editar Proyecto"
        href="{{ route('proyectos.edit', $proyecto) }}">
        <i class="fas fa-pencil-alt m-auto">
        </i>
    </a>
</td>
<td>
    @if (empty($proyecto->puntuacion))
        <a class="btn btn-warning" data-toggle="tooltip" data-placement="top" title="Asignar Profesores"
            href="{{ route('proyectos.asignarUsuarios', $proyecto) }}">
            <i class="fas fa-plus m-auto">
            </i>
        </a>
    @else
        <span class="btn btn-success" data-toggle="tooltip" data-placement="top" title="Proyecto Evaluado">
            <i class="fas fa-check">
            </i></span>
    @endif
</td>
<td>
    <form class="formulario-eliminar" action="{{ route('proyectos.destroy', $proyecto) }}" method="POST">
        @csrf
        @method('DELETE')
        <button class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Borrar Proyecto"
            type="submit"><i class="fas fa-trash m-auto">
            </i></button>
    </form>
</td>
</tr>
@endforeach
</tbody>
</table>
</div>
</div>

</div>